name: "FarmCraft"
author: TheTealViper
version: "1.17.1.a.1"
api-version: 1.16
description: "Custom farming"
main: me.TheTealViper.farmcraft.FarmCraft
softdepend: [HolographicDisplays]
commands:
  farmcraft: